### PR TITLE
Tighten up wording in README

### PR DESCRIPTION
**Pull request by mulkieran**
Mostly try to make it more specific yet still correct.
Fix up some grammer, spelling, etc.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@cathay4t I was trying to understand the intended relations between the daemon and the plugins a bit better. Are my changes still correct? And I have a question...if the collector only collects raw events, how does the parser end up receiving synthetic events as well? Also, in your formulation is the daemon merely a distributor, i.e., is its primary role just to gather up events and figure out where to send them based on the filters, or does it have more added value? Also, do you think of filtering as requiring an ```n``` * ```m``` size set of filters, where ```n``` is the number of collectors plugins, and ```m``` is the number of parser plugins?

**Comment by cathay4t** [comment]
@mulkieran Thanks for the kind review and PR.

> I was trying to understand the intended relations between the daemon and the plugins a bit better. Are my changes still correct?

Yes. They are much better than my lame words.

> And I have a question...if the collector only collects raw events, how does the parser end up receiving synthetic events as well?

The code does not allow parser plugin handle synthetic events yet, but the design is to allow plugin  add another synthetic event base on existing ones. Example, a SCSI sector hardware error event parsed by `scsi` plugin, `block` plugin hooked on `scsi` synthetic events then adds events for impacted partition. `file` system hooked on `block` synthetic events then adds events for impacted file system.

> Also, in your formulation is the daemon merely a distributor, i.e., is its primary role just to gather up events and figure out where to send them based on the filters, or does it have more added value?

The daemon is just a distributor and handle all the heave works about IPC and threading.

> Also, do you think of filtering as requiring an n * m size set of filters, where n is the number of collectors plugins, and m is the number of parser plugins?

I am not quite understand the question, could you please elaborate? Thank you.

**Comment by mulkieran** [comment]
Thanks! I'm not sure my question about filters was a good one, actually, I'll think about it a bit more.

**Comment by cathay4t** [comment]
Merged the PR.
Thanks.
Let me know if you have any question or suggestions.

**Pull request merged**
